- name: Download e unzip do pacote Nimbus (.rpm)
  ansible.builtin.unarchive:
    src: http://www.portalprodeb.ba.gov.br/ftp/cosao/instalacao/CA_UIM/Linux/nimsoft-robot.x86_64.rpm.zip
    dest: /tmp
    remote_src: yes

#  get_url:
#    url="http://www.portalprodeb.ba.gov.br/ftp/cosao/instalacao/CA_UIM/Linux/nimsoft-robot.x86_64.rpm"
#    dest="/opt/nimsoft-robot.x86_64.rpm"
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- name: Instalação do Nimbus Agent
  ansible.builtin.yum:
    name: /tmp/nimsoft-robot.x86_64.rpm
    state: present
    disable_gpg_check: True
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'


- name: Download do pacote Nimbus (.deb)
  get_url:
    url="http://www.portalprodeb.ba.gov.br/ftp/cosao/instalacao/CA_UIM/Linux/nimsoft-robot+debian_amd64.deb"
    dest="/tmp/nimsoft-robot.deb"
  when: ansible_distribution == 'Debian'

- name: Download pacote ubuntu
  get_url:
    url="http://www.portalprodeb.ba.gov.br/ftp/cosao/instalacao/CA_UIM/Linux/nimsoft-robot+ubuntu_amd64.deb"
    dest="/tmp/nimsoft-robot.deb"
  when: ansible_distribution == 'Ubuntu'


- name: Instalação do Nimbus Agent (Debian/Ubuntu)
  apt: deb="/tmp/nimsoft-robot.deb"
#    sudo: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Cópia do arquivo de configuração (nms-robot-vars)
  copy:
    src: "{{ role_path }}/files/nms-robot-vars.cfg"
    dest: /opt/nms-robot-vars.cfg

- name: Aplicar configuração do Nimbus
  shell: 
    cmd: /opt/nimsoft/install/RobotConfigurer.sh
   # chdir: /opt/nimsoft/install/

- name: Start service nimbus, if not started
  ansible.builtin.service:
    name: nimbus
    state: started

- name: Ensure absence of old freeze files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /tmp/nimsoft-robot.deb
    - /tmp/nimsoft-robot.x86_64.rpm
    - /opt/nms-robot-vars.cfg


#- name: Download e unzip do arquivo de configuração (nms-robot-vars)
#  ansible.builtin.unarchive:
#    src: http://www.portalprodeb.ba.gov.br/ftp/cosao/instalacao/CA_UIM/Linux/nms-robot-vars.zip
#    dest: /opt
#    remote_src: yes
#    src: /opt/nms-robot-vars.zip