---
- name: Deploy Ceph Cluster
  hosts: all
  become: yes

  roles:
    - ceph-common

- name: Setup Ceph Monitors
  hosts: ceph-mon
  become: yes

  roles:
    - ceph-mon

- name: Setup Ceph OSDs
  hosts: ceph-osd
  become: yes

  roles:
    - ceph-osd