---
- name: Criando inventário temporário
  hosts: localhost
  tasks:
    - ansible.builtin.add_host:
        name: "{{ vm_ip_address }}"
        groups: vm_group_temp

- name: Customização de templates para Administração da COSAO 
  hosts: vm_group_temp
  gather_facts: yes

# Proxy utilizado durante instalações
  environment:
    http_proxy: http://proxy.prodeb.ba.gov.br:3128
    https_proxy: http://proxy.prodeb.ba.gov.br:3128
    no_proxy: "localhost,127.0.0.1,{{ vm_ip_address | ipaddr('network') }}"

  roles:
    - config_common_tools
    - config_agent_nimbus
    - config_agent_trendmicro_ds
    - config_ssh_users  

